{{- $root := . -}}
{{- range $registry := .Values.custom.registries }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $registry.name }}-registry
  namespace: {{ $root.Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- if $registry.job.annotations }}
{{ toYaml  $registry.job.annotations | indent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ $registry.name }}
      {{- if $registry.job.podAnnotations }}
      annotations:
{{ toYaml $registry.job.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if $root.Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "harbor.serviceAccountName" $root }}
      {{- end }}
      restartPolicy: Never
      {{- if $registry.job.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml $registry.job.imagePullSecrets | indent 6 }}
      {{- end }}
      volumes:
      - name: configure-{{ $registry.name }}-registry
        configMap:
          name: {{ $registry.name }}-registry-cm
          defaultMode: 0755
      containers:
      - name: {{ template "harbor.core" $root }}
        image: {{  required "A image is required to run the job that creates registries. The image must have curl and jq installed." $registry.job.image }}
        command: ['sh', '-c', './tmp/configureRegistry.sh']
        env:
        - name: HARBOR_ADMIN_USERNAME
          value: {{ default "admin" $root.Values.adminUsername }}
        - name: HARBOR_ADMIN_PASSWORD
          value: {{ $root.Values.harborAdminPassword }}
        {{- if $registry.accessKey }}
        - name: ACCESS_KEY
          value: {{ $registry.accessKey }}
        {{- end }}
        {{- if $registry.accessSecret }}
        - name: ACCESS_SECRET
          value: {{ $registry.accessSecret }}
        {{- end }}
        volumeMounts:
        - name: configure-{{ $registry.name }}-registry
          mountPath: /tmp
---
{{- end }}