{{- $root := . -}}
{{- range $replication := .Values.core.replicationRules }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $replication.name }}-replication
  namespace: {{ $root.Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install, post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- if $replication.jobAnnotations }}
{{ toYaml  $replication.jobAnnotations | indent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      name: {{ $replication.name }}
      {{- if $replication.jobPodAnnotations }}
      annotations:
{{ toYaml $replication.jobPodAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if $root.Values.serviceAccount.enabled }}
      serviceAccountName: {{ include "harbor.serviceAccountName" $root }}
      {{- end }}
      restartPolicy: Never
      imagePullSecrets:
        - name: reg.vibrenthealth.com
      volumes:
      - name: configure-{{ $replication.name }}-replication
        configMap:
          name: {{ $replication.name }}-replication
          defaultMode: 0755
      containers:
      - name: {{ template "harbor.core" $root }}
        image: reg.vibrenthealth.com/vibrent/utils/debug-utils:master
        command: ['sh', '-c', './tmp/configureReplication.sh']
        env:
        - name: HARBOR_ADMIN_USERNAME
          value: {{ default "admin" $root.Values.adminUsername }}
        - name: HARBOR_ADMIN_PASSWORD
          value: {{ $root.Values.harborAdminPassword }}
        volumeMounts:
        - name: configure-{{ $replication.name }}-replication
          mountPath: /tmp
---
{{- end }}